apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: goapp240910
  janus-idp.io/tekton: goapp240910
  backstage.io/kubernetes-id: goapp240910
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: goapp240910
resources:
- deployment.yaml
- route.yaml
- service.yaml
