apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: goapp240910
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: goapp240910 
  name: goapp240910
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: goapp240910 
